import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBarComponent from "@/components/layout/topBar";
import SideBarComponent from "@/components/layout/sideBar";
import RightSideBarComponent from "@/components/layout/rightSideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TopBarComponent />
                <div className="flex">
                    <div className="flex-[2]">
                        <SideBarComponent />
                    </div>
                    <div className="flex-[12]">{children}</div>
                    <div className="flex-[3]">
                        <RightSideBarComponent />
                    </div>
                </div>
            </body>
        </html>
    );
}
